<?php namespace Nabeghe\NoHtml\Ide\Elements;

/**
 * @method $this accesskey(callable|string $value = 0)
 * @method $this autocapitalize(callable|string $value = 0)
 * @method $this autofocus(callable|bool $value = 0)
 * @method $this class(callable|string $value)
 * @method $this contenteditable(callable|bool|string $value = 0)
 * @method $this contextmenu(callable|string $value = 0)
 * @method $this dir(callable|string $value = 0)
 * @method $this draggable(callable|bool|string $value = 0)
 * @method $this hidden(callable|bool $value = 0)
 * @method $this id(callable|string $value = 0)
 * @method $this inert(callable|bool $value = 0)
 * @method $this inputmode(callable|string $value = 0)
 * @method $this is(callable|string $value = 0)
 * @method $this itemid(callable|string $value = 0)
 * @method $this itemprop(callable|string $value = 0)
 * @method $this itemref(callable|string $value = 0)
 * @method $this itemscope(callable|bool $value = 0)
 * @method $this itemtype(callable|string $value = 0)
 * @method $this lang(callable|string $value = 0)
 * @method $this nonce(callable|string $value = 0)
 * @method $this part(callable|string $value = 0)
 * @method $this popover(callable|string $value = 0)
 * @method $this role(callable|string $value = 0)
 * @method $this slot(callable|string $value = 0)
 * @method $this spellcheck(callable|bool|string $value = 0)
 * @method $this style(callable|string $value = 0)
 * @method $this tabindex(callable|int $value = 0)
 * @method $this title(callable|string $value = 0)
 * @method $this translate(callable|string $value = 0)
 *
 * @method $this onabort(callable|string $value)
 * @method $this onautocomplete(callable|string $value)
 * @method $this onautocompleteerror(callable|string $value)
 * @method $this onblur(callable|string $value)
 * @method $this oncancel(callable|string $value)
 * @method $this oncanplay(callable|string $value)
 * @method $this oncanplaythrough(callable|string $value)
 * @method $this onchange(callable|string $value)
 * @method $this onclick(callable|string $value)
 * @method $this onclose(callable|string $value)
 * @method $this oncontextmenu(callable|string $value)
 * @method $this oncuechange(callable|string $value)
 * @method $this ondblclick(callable|string $value)
 * @method $this ondrag(callable|string $value)
 * @method $this ondragend(callable|string $value)
 * @method $this ondragenter(callable|string $value)
 * @method $this ondragexit(callable|string $value)
 * @method $this ondragleave(callable|string $value)
 * @method $this ondragover(callable|string $value)
 * @method $this ondragstart(callable|string $value)
 * @method $this ondrop(callable|string $value)
 * @method $this ondurationchange(callable|string $value)
 * @method $this onemptied(callable|string $value)
 * @method $this onended(callable|string $value)
 * @method $this onerror(callable|string $value)
 * @method $this onfocus(callable|string $value)
 * @method $this oninput(callable|string $value)
 * @method $this oninvalid(callable|string $value)
 * @method $this onkeydown(callable|string $value)
 * @method $this onkeypress(callable|string $value)
 * @method $this onkeyup(callable|string $value)
 * @method $this onload(callable|string $value)
 * @method $this onloadeddata(callable|string $value)
 * @method $this onloadedmetadata(callable|string $value)
 * @method $this onloadstart(callable|string $value)
 * @method $this onmousedown(callable|string $value)
 * @method $this onmouseenter(callable|string $value)
 * @method $this onmouseleave(callable|string $value)
 * @method $this onmousemove(callable|string $value)
 * @method $this onmouseout(callable|string $value)
 * @method $this onmouseover(callable|string $value)
 * @method $this onmouseup(callable|string $value)
 * @method $this onmousewheel(callable|string $value)
 * @method $this onpause(callable|string $value)
 * @method $this onplay(callable|string $value)
 * @method $this onplaying(callable|string $value)
 * @method $this onprogress(callable|string $value)
 * @method $this onratechange(callable|string $value)
 * @method $this onreset(callable|string $value)
 * @method $this onresize(callable|string $value)
 * @method $this onscroll(callable|string $value)
 * @method $this onseeked(callable|string $value)
 * @method $this onseeking(callable|string $value)
 * @method $this onselect(callable|string $value)
 * @method $this onshow(callable|string $value)
 * @method $this onsort(callable|string $value)
 * @method $this onstalled(callable|string $value)
 * @method $this onsubmit(callable|string $value)
 * @method $this onsuspend(callable|string $value)
 * @method $this ontimeupdate(callable|string $value)
 * @method $this ontoggle(callable|string $value)
 * @method $this onvolumechange(callable|string $value)
 * @method $this onwaiting(callable|string $value)
 * @method $this onwheel(callable|string $value)
 */
class MainElement extends \Nabeghe\NoHtml\Nodes\Element
{
}