<?php declare(strict_types=1);

namespace Nabeghe\NoHtml\Tests\Unit;

use Nabeghe\NoHtml\Nodes\Unescapable;
use Nabeghe\NoHtml\NoHtml as N;
use Nabeghe\NoHtml\Tests\Fixtures\Css;
use Nabeghe\NoHtml\Tests\Fixtures\Items;

class NoHtmlTest extends \PHPUnit\Framework\TestCase
{
    const EXPECTED_HTML = <<<EOD
        <!DOCTYPE html><html lang="en"><head><meta charset="utf-8" /><meta name="viewport" charset="width=device-width, initial-scale=1.0" /><title>No HTML for PHP by Nabeghe</title><script src="https://cdn.tailwindcss.com"></script></head><body><header class="bg-gray-900 text-white py-6 text-center"><h1 class="text-3xl font-bold">No HTML for PHP by Nabeghe</h1><nav class="mt-2 space-x-4"><a href="#intro" class="over:underline">Intro</a><a href="#table" class="hover:underline">Table</a><a href="#form" class="hover:underline">Form</a></nav></header><main class="max-w-4xl mx-auto p-6 bg-white mt-6 rounded-lg shadow-md space-y-10"><section id="intro"><h2 class="text-2xl font-semibold mb-4">Introduction</h2><p class="mb-4">There are many PHP-based DSLs for HTML out there  but **NoHTML** takes a different route in both behavior and structure.
        At its core, there&apos;s a class where each method corresponds to an HTML element.
        These methods can be used in both static and instance contexts.
        Each method accepts a variadic list of arguments representing the element’s children.
        The return value of every method is an instance of the `Nabeghe\NoHtml\Nodes\Element` class,
        whose methods map to the element&apos;s attributes, following a **Fluent Builder** pattern.</p><p>This items generated by callback</p><ul data-template="Item {n}" class="list-disc list-inside mb-4"><li>Item 01</li><li>Item 02</li><li>Item 03</li><li>Item 04</li><li>Item 05</li><li>Item 06</li><li>Item 07</li><li>Item 08</li><li>Item 09</li><li>Item 10</li></ul></section><section id="table"><h2 class="text-2xl font-semibold mb-4">Details</h2><div class="overflow-x-auto"><table class="min-w-full border border-gray-300 rounded-md"><tr class="hover:bg-gray-100"><td class="border border-gray-300 px-4 py-2">Github</td><td class="border border-gray-300 px-4 py-2"><a href="https://github.com/nabeghe/nohtml-php" title="No HTML">https://github.com/nabeghe/nohtml-php</a></td></tr><tr class="hover:bg-gray-100"><td class="border border-gray-300 px-4 py-2">License</td><td class="border border-gray-300 px-4 py-2">MIT</td></tr></table></div></section><section id="form"><h2 class="text-2xl font-semibold mb-4">Contact Us</h2><form action="#" method="post" class="space-y-4"><div><label for="name" class="block font-medium">Name:</label><input type="text" id="name" name="name" placeholder="Enter your name" class="w-full border border-gray-300 rounded px-3 py-2" /></div><div><label for="email" class="block font-medium">Email:</label><input type="text" id="email" name="email" placeholder="Your email" class="w-full border border-gray-300 rounded px-3 py-2" /></div><div><label for="message" class="block font-medium">Nessage:</label><textarea id="message" name="message" placeholder="Type your message here..." class="w-full border border-gray-300 rounded px-3 py-2"></textarea></div><div class="flex items-center space-x-2"><input type="checkbox" id="agree" name="agree" placeholder="Your email" checked class="h-4 w-4 text-blue-600 rounded" /><label for="agree" class="select-none">I agree to the terms</label></div><button type="submit" class="bg-blue-600 text-white rounded px-5 py-2 hover:bg-blue-700 transition">Submit</button></form></section></main><footer class="bg-gray-900 text-white text-center py-6 mt-10">&copy; No HTML - Built with ❤️ by <a href="https://elatel.ir">https://elatel.ir</a></footer></body></html>
        EOD;

    public function testApp()
    {
        $app = N::html(
            N::head(
                N::meta()->charset('utf-8'),
                N::meta()->name('viewport')->charset('width=device-width, initial-scale=1.0'),
                N::title('No HTML for PHP by Nabeghe'),
                N::script()->src('https://cdn.tailwindcss.com'),
            ),
            N::body(
                N::header(
                    N::h1('No HTML for PHP by Nabeghe')->class('text-3xl font-bold'),
                    N::nav(
                        N::a('Intro')->href('#intro')->class('over:underline'),
                        N::a('Table')->href('#table')->class('hover:underline'),
                        N::a('Form')->href('#form')->class('hover:underline'),
                    )->class('mt-2 space-x-4'),
                )->class('bg-gray-900 text-white py-6 text-center'),
                N::main(
                    N::section(
                        N::h2('Introduction')->class('text-2xl font-semibold mb-4'),
                        N::p(<<<EOD
                            There are many PHP-based DSLs for HTML out there  but **NoHTML** takes a different route in both behavior and structure.
                            At its core, there's a class where each method corresponds to an HTML element.
                            These methods can be used in both static and instance contexts.
                            Each method accepts a variadic list of arguments representing the element’s children.
                            The return value of every method is an instance of the `Nabeghe\NoHtml\Nodes\Element` class,
                            whose methods map to the element's attributes, following a **Fluent Builder** pattern.
                            EOD
                        )->class('mb-4'),
                        N::p('This items generated by callback'),
                        N::ul([Items::class, 'generate'])->data('template', 'Item {n}')->class('list-disc list-inside mb-4'),
                    )->id('intro'),
                    N::section(
                        N::h2('Details')->class('text-2xl font-semibold mb-4'),
                        N::div(
                            N::table(
                                N::tr(
                                    N::td('Github')->class([Css::class, 'tableCell']),
                                    N::td(
                                        N::a('https://github.com/nabeghe/nohtml-php')->href('https://github.com/nabeghe/nohtml-php')->title('No HTML'),
                                    )->class([Css::class, 'tableCell']),
                                )->class([Css::class, 'tableRow']),
                                N::tr(
                                    N::td('License')->class([Css::class, 'tableCell']),
                                    N::td('MIT')->class([Css::class, 'tableCell']),
                                )->class([Css::class, 'tableRow']),
                            )->class('min-w-full border border-gray-300 rounded-md'),
                        )->class('overflow-x-auto'),
                    )->id('table'),
                    N::section(
                        N::h2('Contact Us')->class('text-2xl font-semibold mb-4'),
                        N::form(
                            N::div(
                                N::label('Name:')->for('name')->class('block font-medium'),
                                N::input()->type('text')->id('name')->name('name')->placeholder('Enter your name')->class('w-full border border-gray-300 rounded px-3 py-2'),
                            ),
                            N::div(
                                N::label('Email:')->for('email')->class('block font-medium'),
                                N::input()->type('text')->id('email')->name('email')->placeholder('Your email')->class('w-full border border-gray-300 rounded px-3 py-2'),
                            ),
                            N::div(
                                N::label('Nessage:')->for('message')->class('block font-medium'),
                                N::textarea()->id('message')->name('message')->placeholder('Type your message here...')->class('w-full border border-gray-300 rounded px-3 py-2'),
                            ),
                            N::div(
                                N::input()->type('checkbox')->id('agree')->name('agree')->placeholder('Your email')->checked(true)->class('h-4 w-4 text-blue-600 rounded'),
                                N::label('I agree to the terms')->for('agree')->class('select-none'),
                            )->class('flex items-center space-x-2'),
                            N::button('Submit')->type('submit')->class('bg-blue-600 text-white rounded px-5 py-2 hover:bg-blue-700 transition'),
                        )->action('#')->method('post')->class('space-y-4'),
                    )->id('form'),
                )->class('max-w-4xl mx-auto p-6 bg-white mt-6 rounded-lg shadow-md space-y-10'),
                N::footer(
                    new Unescapable('&copy; No HTML - Built with ❤️ by <a href="https://elatel.ir">https://elatel.ir</a>'),
                )->class('bg-gray-900 text-white text-center py-6 mt-10')
            ),
        )->lang('en');

        $app = '<!DOCTYPE html>'.$app;

        $this->assertSame(self::EXPECTED_HTML, $app);
    }
}